java:
  runtime:
    version:11.0.3
server:
  port: 1234
  servlet:
    context-path: /lms
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: asmitha
  jackson.deserialization.fail-on-unknown-properties: true
  mvc.hiddenmethod.filter.enabled: true
  main.allow-bean-definition-overriding: true
  #hibernate ddl Auto for CURDOperations
  jpa.hibernate.ddl-auto: none
  #For UI refresh without restarting server
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

logging:
  file:
    name: lmsservice.log
    path: ./
layout:
  pageInfo:
    program:
      idField: "programId"
      title: "Programs"
      searchField: "programName"
      fieldNames:
        programId: "Program Id"
        programName: "Program Name"
        programDescription: "Program Description"
        programStatus: "Program Status"
    programbatch:   
      idField: "batchId"
      title: "Batches"
      searchField: "batchName"
      fieldNames:
        batchId: "Batch Id"
        batchName: "Batch Name"
        batchDescription: "Batch Description"
        batchStatus: "Batch Status"
        batchProgramId: "Program Id"
        batchNoOfClasses: "No.of.classes"
    class:
      idField: "csId"
      title: "Classes"
      searchField: "classTopic"
      fieldNames:
        csId: "Class Id"
        batchId: "Batch Id"
        classNo: "Class No"
        classDate: "Class Date"
        classTopic: "Class Topic"
        classStaffId: "Staff Id"
        classDescription: "Description"
        classComments: "Comments"
        classNotes: "Notes"
        classRecordingPath: "Recording"
    attendance:
      idField: "attId"
      title: "Attendance"
      searchField: "classId"
      fieldNames:
        attId: "Attendance Id"
        classId: "Class Id"
        studentId: "Student Id"
        attendance: "Attendance"
    assignment:
      idField: "assignmentId"
      title: "Assignments"
      searchField: "Batch Id"
      fieldNames:
        assignmentId: "Assignment Id"
        assignmentName: "Assignment Name"
        assignmentDescription: "Assignment Description"
        dueDate: "Assignment Due Date"